### ISSUE TITLE
Nuova release di ncrad_grib

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/ncrad_grib#1]
@virginiapoli ho visto che, dopo l'ultima release (v0.1-2), c'è stata una commit abbastanza importante (1d512e531370fffef8b655bba11da4fe1d28dfc3).

Ti chiedo se posso fare una nuova release, in modo da pacchettizzare anche per Fedora 40.

 Il pacchetto compila senza problemi su ogni distribuzione anche se, essendo in Python e non essendoci test, ha poca rilevanza.

**Comment by virginiapoli** [comment]
Certamente.
